//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DATA_AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.borrows = new HashSet<borrow>();
            this.publishers = new HashSet<publisher>();
        }
    
        public int bk_id { get; set; }
        public string bk_name { get; set; }
        public Nullable<int> bk_pages { get; set; }
        public string map_plates { get; set; }
        public Nullable<int> bk_rate { get; set; }
        public string bk_notes { get; set; }
        public string language { get; set; }
        public Nullable<int> bk_volume { get; set; }
        public Nullable<System.DateTime> publication_year { get; set; }
        public Nullable<int> authors_id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> bk_entry_date { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> bk_parts { get; set; }
        public Nullable<int> categories_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual categorie categorie { get; set; }
        public virtual ICollection<borrow> borrows { get; set; }
        public virtual ICollection<publisher> publishers { get; set; }
    }
}
