//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DATA_AL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities5 : DbContext
    {
        public LibraryEntities5()
            : base("name=LibraryEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<borrow> borrows { get; set; }
        public DbSet<borrower> borrowers { get; set; }
        public DbSet<categorie> categories { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<publisher> publishers { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
