//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DATA_AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        public publisher()
        {
            this.books = new HashSet<book>();
        }
    
        public int pp_id { get; set; }
        public string pp_name { get; set; }
        public string pp_address { get; set; }
    
        public virtual ICollection<book> books { get; set; }
    }
}
