//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.DATA_AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.logs = new HashSet<log>();
        }
    
        public int sf_id { get; set; }
        public string sf_user { get; set; }
        public string sf_pass { get; set; }
        public string sf_ssn { get; set; }
        public string sf_phone { get; set; }
        public string sf_adress { get; set; }
        public string accessablity { get; set; }
    
        public virtual ICollection<log> logs { get; set; }
    }
}
