//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_system.DATA_AL
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int staff_id { get; set; }
        public int lg_id { get; set; }
        public System.DateTime lg_date { get; set; }
        public string process { get; set; }
        public string table_name { get; set; }
        public string opration_kind { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
